### ISSUE TITLE
Uzupełnienie Readme

### ISSUE THREAD

**Issue by efiku** [CodersCommunity/forum.pasja-informatyki.local#2]
Pasuje uzupełnić / przebudować README.
Wołam @CodersCommunity/administration, @CodersCommunity/forum, @CodersCommunity/users 

- Brakuje informacji o tym jak to postawić.
- Co jest wymagane
- Co zmienić w hostach aby działało.
- Pasuje dodać CONTRIBUTING.md z zasadami
- Ustalić zasady, branche itd.

**forum/ -** document root apache, tu będzie stać całe q2a.
**tests/ -** nasze testy 

Na serwerze zainstalowano:
xdebug
Composer ( dla phpunit itd)

Dane do bazy mysql:
_(znajdują się w pliku ansible/vars/all.yml)_
```
mysql:
    root_password: root
    database: forum
    user: test
    password: test
```

Wymagane:
* VirtualBox
* vagrant >=1.5
* NFS server.
* /etc/hosts → 192.168.122.122 forum.pasja-informatyki.local
