### ISSUE TITLE
[Widok pytania] Brak zawijania, gdy link w treści lub komentarzu jest zbyt długi.

### ISSUE THREAD

**Issue by xandros15** [CodersCommunity/forum.pasja-informatyki.local#85]
W niektórych pytaniach występuje następujący błąd:

![image](https://cloud.githubusercontent.com/assets/10834079/21011534/0f55aaf8-bd52-11e6-82bc-d478f076b230.png)

Pewnie wystarczy wprowadzić coś w stylu: 
```css
.qa-c-item-content .entry-content {
    word-wrap: break-word;
}
``` 
ale mogę się mylić.

**Comment by efiku** [comment]
Jak wrócę do domu to zerkrne :) oby to tylko css Haha


Krzysztof Pazdur

08.12.2016 14:29 "xandros15" <notifications@github.com> napisał(a):

**Comment by efiku** [comment]
@xandros15 możesz zrobić PR?

Wychodzi na to że:

```css
.qa-c-item-content .entry-content a{
    word-wrap: break-word;
}
```

daje rade, zerknij.
